import { Division } from '../types/dewey'

export const Divisions: Division[] = [
  { code: '000', name: 'Computer science, knowledge and systems' },
  { code: '010', name: 'Bibliography' },
  { code: '020', name: 'Library and information sciences' },
  { code: '030', name: 'Encyclopedias and books of facts' },
  { code: '040', name: 'Unassigned (formerly Biographies)' },
  { code: '050', name: 'Magazines, journals and serials' },
  { code: '060', name: 'Associations, organizations and museums' },
  { code: '070', name: 'News media, journalism and publishing' },
  { code: '080', name: 'Quotations' },
  { code: '090', name: 'Manuscripts and rare books' },
  { code: '100', name: 'Philosophy' },
  { code: '110', name: 'Metaphysics' },
  { code: '120', name: 'Epistemology' },
  { code: '130', name: 'Parapsychology and occultism' },
  { code: '140', name: 'Philosophical schools of thought' },
  { code: '150', name: 'Psychology' },
  { code: '160', name: 'Philosophical logic' },
  { code: '170', name: 'Ethics' },
  { code: '180', name: 'Ancient, medieval, and Eastern philosophy' },
  { code: '190', name: 'Modern Western philosophy (19th-century, 20th-century)' },
  { code: '200', name: 'Religion' },
  { code: '210', name: 'Philosophy and theory of religion' },
  { code: '220', name: 'The Bible' },
  { code: '230', name: 'Christianity' },
  { code: '240', name: 'Christian practice and observance' },
  { code: '250', name: 'Christian orders and local church' },
  { code: '260', name: 'Christian social and ecclesiastical theology' },
  { code: '270', name: 'History of Christianity' },
  { code: '280', name: 'Christian denominations' },
  { code: '290', name: 'Other religions' },
  { code: '300', name: 'Social sciences, sociology and anthropology' },
  { code: '310', name: 'Statistics' },
  { code: '320', name: 'Political science' },
  { code: '330', name: 'Economics' },
  { code: '340', name: 'Law' },
  { code: '350', name: 'Public administration and military science' },
  { code: '360', name: 'Social problems and social services' },
  { code: '370', name: 'Education' },
  { code: '380', name: 'Commerce, communications and transportation' },
  { code: '390', name: 'Customs, etiquette and folklore' },
  { code: '400', name: 'Language' },
  { code: '410', name: 'Linguistics' },
  { code: '420', name: 'English and Old English languages' },
  { code: '430', name: 'German and related languages' },
  { code: '440', name: 'French and related languages' },
  { code: '450', name: 'Italian, Romanian and related languages' },
  { code: '460', name: 'Spanish, Portuguese, Galician' },
  { code: '470', name: 'Latin and Italic languages' },
  { code: '480', name: 'Classical and modern Greek languages' },
  { code: '490', name: 'Other languages' },
  { code: '500', name: 'Science' },
  { code: '510', name: 'Mathematics' },
  { code: '520', name: 'Astronomy' },
  { code: '530', name: 'Physics' },
  { code: '540', name: 'Chemistry' },
  { code: '550', name: 'Earth sciences and geology' },
  { code: '560', name: 'Fossils and prehistoric life' },
  { code: '570', name: 'Biology' },
  { code: '580', name: 'Plants' },
  { code: '590', name: 'Animals (Zoology)' },
  { code: '600', name: 'Technology' },
  { code: '610', name: 'Medicine and health' },
  { code: '620', name: 'Engineering' },
  { code: '630', name: 'Agriculture' },
  { code: '640', name: 'Home and family management' },
  { code: '650', name: 'Management and public relations' },
  { code: '660', name: 'Chemical engineering' },
  { code: '670', name: 'Manufacturing' },
  { code: '680', name: 'Manufacture for specific uses' },
  { code: '690', name: 'Construction of buildings' },
  { code: '700', name: 'Arts' },
  { code: '710', name: 'Area planning and landscape architecture' },
  { code: '720', name: 'Architecture' },
  { code: '730', name: 'Sculpture, ceramics and metalwork' },
  { code: '740', name: 'Graphic arts and decorative arts' },
  { code: '750', name: 'Painting' },
  { code: '760', name: 'Printmaking and prints' },
  { code: '770', name: 'Photography, computer art, film, video' },
  { code: '780', name: 'Music' },
  { code: '790', name: 'Outline of sports, games and entertainment' },
  { code: '800', name: 'Literature, rhetoric and criticism' },
  { code: '810', name: 'American literature in English' },
  { code: '820', name: 'English and Old English literatures' },
  { code: '830', name: 'German and related literatures' },
  { code: '840', name: 'French and related literatures' },
  { code: '850', name: 'Italian, Romanian and related literatures' },
  { code: '860', name: 'Spanish, Portuguese, Galician literatures' },
  { code: '870', name: 'Latin and Italic literatures' },
  { code: '880', name: 'Classical and modern Greek literatures' },
  { code: '890', name: 'Other literatures' },
  { code: '900', name: 'History' },
  { code: '910', name: 'Geography and travel' },
  { code: '920', name: 'Biography and genealogy' },
  { code: '930', name: 'History of ancient world (to c. 499)' },
  { code: '940', name: 'History of Europe' },
  { code: '950', name: 'History of Asia' },
  { code: '960', name: 'History of Africa' },
  { code: '970', name: 'History of North America' },
  { code: '980', name: 'History of South America' },
  { code: '990', name: 'History of other areas' },
]
